---

- name: Create folder
  ansible.windows.win_file:
    path: C:\julio_test
    state: directory
# - name: Create a directory if it does not exist
#   file:
#     path: ~/iidk
#     state: directory
#     mode: '0755'

# - name: Update all packages to the latest version
#   apt:
#     upgrade: dist

# - name: Install required packages
#   apt:
#     pkg: "{{ item }}"
#     update_cache: yes
#     state: present
#   with_items: "{{ packages.install }}"

# - name: Purge unwanted packages
#   apt:
#     pkg: "{{ item }}"
#     state: absent
#     purge: yes
#   with_items: "{{ packages.purge }}"

# - name: Pip required packages
#   pip:
#     name: "{{ item }}"
#     state: present
#   with_items: "{{ pip.install }}"
