---

- name: Create a directory if it does not exist
  file:
    path: ~/iidk
    state: directory
    mode: '0755'

- name: Update all packages to the latest version
  yum:
    name: '*'
    state: latest

- name: Install required packages
  yum:
    name: "{{ packages.install }}"
    state: latest

- name: Purge unwanted packages
  yum:
    name: "{{ packages.purge }}"
    state: absent

- name: Pip required packages
  pip:
    name: "{{ item }}"
    state: present
  with_items: "{{ pip.install }}"
